name: dts_mac_host
channels:
  - pytorch
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - transformers
      - fastapi
      - uvicorn[standard]
      - python-multipart
      - pillow
